proto_library(
    name = "imports_proto",
    srcs = ["imports.proto"],
    deps = [
        "//src:a_proto",
        "//src:b_proto",
        "//src:c_proto",
        "//src:d_proto",
        "//src:e_proto",
        "//src:x_proto",
        "//src:y_proto",
        "//src:z_proto",
        "@com_google_protobuf//:any_proto",
        "@google_api_protos//google/api:annotations_proto",
    ],
)
